services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env:
      SA_PASSWORD: StrongPass123!
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    options: >-
      --health-cmd "echo 'SELECT 1' | /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P StrongPass123!"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 10
