name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore TaskManagerAPI.sln

      - name: Build
        run: dotnet build TaskManagerAPI.sln --no-restore --configuration Release

      - name: Build Tests
        run: dotnet build TaskManagerAPI.Tests/TaskManagerAPI.Tests.csproj --no-restore --configuration Release

      - name: Run Test
        run: |
          dotnet vstest TaskManagerAPI.Tests/bin/Release/net9.0/TaskManagerAPI.Tests.dll \
            --logger "console;verbosity=normal"
        env:
            ASPNETCORE_ENVIRONMENT: CI
            ConnectionStrings__DefaultConnection: InMemory
